# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_character_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('level', models.IntegerField(default=1)),
                ('funds', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
                ('small_1', models.IntegerField(default=0)),
                ('small_2', models.IntegerField(default=0)),
                ('small_3', models.IntegerField(default=0)),
                ('small_4', models.IntegerField(default=0)),
                ('small_5', models.IntegerField(default=0)),
                ('small_6', models.IntegerField(default=0)),
                ('medium_1', models.IntegerField(default=0)),
                ('medium_2', models.IntegerField(default=0)),
                ('medium_3', models.IntegerField(default=0)),
                ('medium_4', models.IntegerField(default=0)),
                ('large_1', models.IntegerField(default=0)),
                ('large_2', models.IntegerField(default=0)),
                ('character_id', models.ManyToManyField(to='player.Character')),
                ('dm_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
