# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hideout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='character_id',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='dm_id',
            new_name='dm',
        ),
    ]
