# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('role', models.CharField(max_length=75)),
                ('level', models.IntegerField()),
                ('specialty', models.IntegerField()),
                ('specialty_level', models.IntegerField(default=1)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
