# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_character_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='user_id',
            new_name='user',
        ),
    ]
